#!/usr/bin/env bash
export FJS_DECISION_WORKERS=1 
export DISPATCH_JOB=true 
export RANDOM_SEED=as1234 
export FJS_ACTIVITY_WORKERS=8 
export AWS_ACCESS_KEY_ID=AKIAJ55BPJ5S5QZ3AVKQ 
export AWS_SECRET_ACCESS_KEY="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" 
export ENBALE_SCHEDULER=true 
export ENBALE_JOBQUEUE=true 
export ENBALE_JOURNAL=true 
export JOURNAL_DB_PLUGIN=memory 
npm run test2